In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.4, random_state=1)

Logistic Regression

In [22]:
lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9568845618915159

Decision Tree Classifier

In [23]:
dt = DecisionTreeClassifier()
dt.fit(X_train,y_train)
dt.score(X_test,y_test)

0.8414464534075105

Random Forest

In [24]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9680111265646731

## K-Fold-Cross Validation

In [31]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=4)
kf

KFold(n_splits=4, random_state=None, shuffle=False)

In [32]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8]):
    print(train_index, test_index)

[2 3 4 5 6 7] [0 1]
[0 1 4 5 6 7] [2 3]
[0 1 2 3 6 7] [4 5]
[0 1 2 3 4 5] [6 7]


**Use KFold for our original problem**

In [33]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [38]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=4)

scores_logistic = []
scores_dt = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_dt.append(get_score(DecisionTreeClassifier(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [39]:
scores_logistic

[0.9377777777777778, 0.910913140311804, 0.9576837416481069, 0.9042316258351893]

In [40]:
scores_dt

[0.7888888888888889,
 0.7371937639198218,
 0.8396436525612472,
 0.7505567928730512]

In [41]:
scores_rf

[0.9288888888888889,
 0.9131403118040089,
 0.9665924276169265,
 0.9398663697104677]

Observe that one of the values in each of the list is very near or almost equal to the accuracy that we got from the "train_test_split" with a test size=0.4; the reason being that when 4-Fold validation is done, it basically splits the entire dataset into four parts and the model trains and tests on the 4 permutations of the dataset (divided into 3 parts for training & 1 part for testing). Hence, one of the permutations is ought to be **similar** to the one from "train_test_split".

## cross_val_score function

In [42]:
from sklearn.model_selection import cross_val_score

Logistic regression model performance using cross_val_score

In [44]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target,cv=4)

array([0.93777778, 0.91091314, 0.95768374, 0.90423163])

**decision tree model performance using cross_val_score**

In [47]:
cross_val_score(DecisionTreeClassifier(), digits.data, digits.target,cv=4)

array([0.80222222, 0.74164811, 0.84187082, 0.77282851])

**random forest performance using cross_val_score**

In [48]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target,cv=4)

array([0.93555556, 0.91759465, 0.96213808, 0.92650334])

cross_val_score uses stratifield kfold by default

## Parameter tunning using k fold cross validation

In [49]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target, cv=10)
np.average(scores1)

0.8803476101800124

In [50]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=20),digits.data, digits.target, cv=10)
np.average(scores2)

0.9359993792675356

In [51]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=30),digits.data, digits.target, cv=10)
np.average(scores3)

0.9421198013656114

In [52]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target, cv=10)
np.average(scores4)

0.9404624456859093